server:
  build: '.'
  #command: 'nodemon --exec "npm run lint && npm start"'
  command: 'nodemon'
  environment:
    NODE_ENV: 'dev'
    PORT: 5000
    GH_USERNAME:
    GH_TOKEN:
    SECRET:
    BRANCH_WHITELIST:
    SLACK:
    SLACK_USER:
  ports:
    - '8080:5000'
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '.:/app/server'
    - './example-configs:/configs'
