port: '{{ENV.PORT || 5000}}'
username: '{{ENV.GH_USERNAME}}'
token: '{{ENV.GH_TOKEN}}'
secret: '{{ENV.SECRET || "deploy"}}'
branchWhitelist: '{{ENV.BRANCH_WHITELIST}}'
repoPath: '/repos'
sharedConfigPath: '/configs'
logger:
  type: 'json'
  renderOptions:
    json:
      tagsObject: true
