connection:
  state:
    isSecure: false
plugins:
  hapi-password:
    _priority: -2
  hapi-strategy-loader:
    _priority: -2
    strategies:
      admin:
        scheme: 'password'
        mode: false
        options:
          successEndpoint: '/ui'
          password: '{{secret}}'
          salt: 'asldkjqweljwije01j2lkemaslkj09jkljasdm1oie'
          cookieName: 'deploy'
          ttl: '{{1000 * 60 * 24 * 30}}'
          loginForm:
            name: 'Shipment/Deploy'
  vision:
  './server-plugins/setup':
    _priority: -3
  './server-plugins/update-checker':
    url: 'https://raw.githubusercontent.com/shipment/deploy/master/package.json'
    interval: '{{ 1000 * 60 * 60 * 24 }}'
  hapi-slack:
    _priority: -1
    _enabled: '{{ENV.SLACK || false}}'
    slackHook: '{{ENV.SLACK}}'
    username: '{{ENV.SLACK_USER || "Shipment"}}'
    hideTags: true
    tags:
      - 'warning'
      - 'success'
      - 'error'
      - 'notice'

views:
  path: '{{CWD}}/views'
  engines:
    html: 'handlebars'
